-- ====================================================================================
-- MIGRACIÓN DE CONTRASEÑAS - Script SQL para inicializar contraseñas existentes
-- ====================================================================================
-- Este script utiliza PHP password_hash() para generar el hash de la cédula
-- Si deseas ejecutar esto directamente en SQL, debes usar los hashes generados por PHP
--
-- OPCIÓN 1: Usar inicialización automática (RECOMENDADO)
-- El sistema ahora inicializa automáticamente las contraseñas NULL con la cédula hasheada
-- cuando el usuario busca su cédula por primera vez. No es necesario ejecutar este script.
--
-- OPCIÓN 2: Inicializar manualmente desde PHP Artisan/CLI (Si el proyecto lo soporta)
-- php -r "$pdo = new PDO(...); $stmt = $pdo->query('SELECT cedula FROM usuarios WHERE contrasenia IS NULL');
--        while($row = $stmt->fetch()) {
--            $hash = password_hash($row['cedula'], PASSWORD_DEFAULT);
--            $update = $pdo->prepare('UPDATE usuarios SET contrasenia = ? WHERE cedula = ?');
--            $update->execute([$hash, $row['cedula']]);
--        }"
--
-- OPCIÓN 3: Usar PHPMyAdmin para ejecutar actualización (Requiere bcrypt UDF)
-- Nota: Esta opción requiere una extensión personalizada de MySQL para bcrypt
-- No es recomendada para producción sin soporte específico de tu servidor MySQL
--
-- ====================================================================================

-- Aquí van los registros con hashes de contraseñas que necesites insertar manualmente
-- Ejemplo: Si tienes un usuario con cédula 1234567890, usa:
-- UPDATE usuarios SET contrasenia = '$2y$10$...' WHERE cedula = '1234567890'
-- (Reemplaza el hash con el generado por PHP password_hash('1234567890', PASSWORD_DEFAULT))
